### ISSUE TITLE
Is this meant for the general public?

### ISSUE THREAD

**Issue by con-f-use** [serokell/vault-secrets#29]
Is this meant for usage outside of serokell? I'm asking because I find the [custom registry](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L5) bit somewhat problematic and also am scratching my head about the potentially [custom nix](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L29) for the [dev shell](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L41).

**Comment by rvem** [comment]
> Is this meant for usage outside of serokell?

Yes

> I'm asking because I find the [custom registry bit](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L5) problematic and also am scratching my hand about the potentially [custom nix](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L29) for the [dev shell](https://github.com/serokell/vault-secrets/blob/e20e124551d1ab2f9445033e0596e9daf7d23b5e/flake.nix#L41).

Uh, this is probably something that needs to be updated, there are really no requirements on a specific `nixpkgs` and specific `nix`, this "custom nix" pinning is rather a leftover, AFAICS

**Comment by rvem** [comment]
> there are really no requirements on a specific `nixpkgs`

I'd even rather suggest using `vault-secrets` as follows:
```
inputs = {
  ...
  vault-secrets = {
    url = "github:serokell/vault-secrets";
    inputs.nixpkgs.follows = "nixpkgs";
  };
  ...
};
```
To avoid having an additional `nixpkgs` dependency in your `flake.lock`
