### ISSUE TITLE
Re-write `write_scerets.py` as shell script

### ISSUE THREAD

**Issue by con-f-use** [serokell/vault-secrets#37]
Since python3 is a pretty hefty dependency and the systemd service already depends on jq, you could replace `./scripts/write_secrets.py` by something like this: https://github.com/con-f-use/vault-secrets/commit/de29e48ca75c657c0ed7bd68b7980df5522baeb8#diff-b57d2c49799576d89cb44bee6c607915e952db064522333fa9f423fb88358483

**Comment by rvem** [comment]
Good point. To be fair, I'm not even sure why this script was written using `python`, but getting rid of the `python` dependency should be straightforward given that this script is mostly trivial.
Since you already have related changes, I'd happily review your PR :sweat_smile:
